options:
  docker: true

definitions:
  updateOS: &update
    apt-get update
  printVersion: &version
    node --version && npm --version
  confBuildx: &buildx
    docker --version &&
    docker pull docker/buildx-bin:latest &&
    docker container create --name buildx docker/buildx-bin:latest docker buildx version &&
    mkdir -p /usr/libexec/docker/cli-plugins/ &&
    docker container cp buildx:/buildx /usr/libexec/docker/cli-plugins/docker-buildx &&
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes &&
    docker buildx create --use &&
    docker buildx version
  awsEcrLogin: &ecrlogin
    aws ecr get-login-password | docker login --password-stdin --username AWS "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
  buildApp: &appcontainer
    docker buildx build --push --platform linux/arm64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${ENV} -f Dockerfile .
  buildProxyWeb: &proxywebcontainer
    sed -i='' -e "s|<SERVER_NAME>|${SERVER_NAME_WEB}|" proxy/conf.d/web.conf &&
    sed -i='' -e "s|<SERVER_NAME>|${SERVER_NAME_WEB}|" proxy/conf.d/default.conf &&
    docker buildx build --push --platform linux/arm64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${ENV} -f proxy/Dockerfile ./proxy
  build: &build
    #CI=false REACT_APP_DEVTOOLS=$REACT_APP_DEVTOOLS REACT_APP_SITE24X7_KEY=$REACT_APP_SITE24X7_KEY REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN npm run build
    CI=false npm run build
  steps:
    - step: &test
        name: Test
        image: node:16
        runs-on:
          - 'self.hosted'
          - 'linux'
          - 'web'
        size: 1x
        script:
          - *update
          - *version
          - npm install --no-audit
          #- npm run test
        artifacts:
          - node_modules/**
pipelines:
  branches:
    nextjs:
      - step: *test
      - step:
          name: Build
          image: node:16
          runs-on:
            - 'self.hosted'
            - 'linux'
            - 'web'
          size: 2x
          script:
            - *update
            - *version
            # RPC config
            - cp -p ./src/Assets/networks/rpc_config_dev.json ./src/Assets/networks/rpc_config.json
            # Build frontend
            - *build
          artifacts:
            - .next/**
      # - step:
      #     name: Upload to S3
      #     image: amazon/aws-cli
      #     runs-on:
      #       - 'self.hosted'
      #       - 'linux'
      #       - 'web'
      #     # Copy RPC config to Admin S3 Bucket
      #     script:
      #       - aws s3 cp ./src/Assets/networks/rpc_config_dev.json s3://dev-ebisusbay-admin-storage/rpc_config.json
      - step:
          name: Build containers
          image: amazon/aws-cli
          deployment: DevelopmentNext
          services:
            - docker
          runs-on:
            - 'self.hosted'
            - 'linux'
            - 'web'
          size: 1x
          script:
            # Install and configure Docker Buildx
            - *buildx
            # Login to ECR
            - *ecrlogin
            # Build container images and push to ECR repositorys and push to ECR repository
            - *appcontainer
            - *proxywebcontainer
      - step:
         name: Deploy
         image: alpine:latest
         runs-on:
           - 'self.hosted'
           - 'linux'
           - 'web'
         size: 1x
         clone:
           enabled: false
         script:
           # deploy next-ebisusbay-web-arm64-us-east-1 / next.ebisusbay.biz
           - apk add --no-cache curl
           - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"ref_type\":\"branch\",\"type\":\"pipeline_ref_target\",\"ref_name\":\"dev\"}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
definitions:
  services:
    docker:
      # default memory is 1024MB
      memory: 3072
      image: docker:dind
