definitions:
  updateOS: &update
    apt-get update
  printVersion: &version
    node --version && npm --version
  build: &build
    #CI=false REACT_APP_DEVTOOLS=$REACT_APP_DEVTOOLS REACT_APP_SITE24X7_KEY=$REACT_APP_SITE24X7_KEY REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN npm run build
    CI=false npm run build

  steps:
    - step: &test
        name: Test
        image: node:16
        runs-on:
          - 'self.hosted'
          - 'linux'
          - 'web'
        size: 1x
        script:
          - *update
          - *version
          - npm install --no-audit
          #- npm run test
        artifacts:
          - node_modules/**
    - step: &deploy
        name: Deploy
        image: amazon/aws-cli
        deployment: changethis
        runs-on:
          - 'self.hosted'
          - 'linux'
          - 'web'
        size: 1x
        #trigger: manual
        clone:
          enabled: false
        script:
          # AWS S3 deploy
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              LOCAL_PATH: 'build'
              DELETE_FLAG: 'true'
          # Custom No-Store metadata for index.html
          - aws s3 cp build/index.html s3://${S3_BUCKET}/index.html --metadata-directive REPLACE --cache-control No-Store
          # AWS CloudFront create invalidation
          - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $CF_DIST_ID
              PATHS: '/img/* /static/* /3dslothty-refunds.csv /404.html /android-chrome-192x192.png /android-chrome-512x512.png /apple-touch-icon.png /asset-manifest.json /browserconfig.xml /favicon-16x16.png /favicon-32x32.png /favicon.ico /favicon.png /index.html /manifest.json /mstile-150x150.png /robots.txt /safari-pinned-tab.svg /site.webmanifest /sitemap.xml /tos.html /vector-face.svg'

pipelines:
  custom: # Pipelines that can only be triggered manually or by schedule
    deploy-to-nextjs:
      - step: *test
      - step:
          name: Build
          image: node:16
          deployment: DevelopmentNextBuildStep
          runs-on:
            - 'self.hosted'
            - 'linux'
            - 'web'
          size: 2x
          script:
            - *update
            - *version
            # Increase memory
            - export NODE_OPTIONS=--max_old_space_size=3072
            # RPC config
            - cp -p ./src/Assets/networks/rpc_config_dev.json ./src/Assets/networks/rpc_config.json
            # Build frontend
            - *build
          artifacts:
            - build/**
      # - step:
      #     name: Upload to S3
      #     image: amazon/aws-cli
      #     runs-on:
      #       - 'self.hosted'
      #       - 'linux'
      #       - 'web'
      #     # Copy RPC config to Admin S3 Bucket
      #     script:
      #       - aws s3 cp ./src/Assets/networks/rpc_config_dev.json s3://dev-ebisusbay-admin-storage/rpc_config.json
      - step:
          <<: *deploy
          deployment: DevelopmentNext
