###################
### Build image ###
###################

FROM node:16 as build

# Install build dependencies for underlying OS
RUN apt-get update && apt-get install -y g++ build-essential

# Print Node.js & npm versions
RUN node --version
RUN npm --version

# Install the dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --no-audit

# Build the project
COPY .husky ./.husky
COPY pages ./pages
COPY public ./public
COPY src ./src
COPY next.config.js ./

RUN NEXT_PUBLIC_ENV=development npm run build

#####################
### Runtime image ###
#####################

#FROM node:16-slim
FROM node:16.15.0-slim

# Update packages
RUN apt-get update && apt-get install -y git curl procps htop net-tools

# Print Node.js version
RUN node --version

# Copy the required files from the build step
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/.husky ./.husky
COPY --from=build /usr/src/app/pages ./pages
COPY --from=build /usr/src/app/public ./public
COPY --from=build /usr/src/app/src ./src
COPY --from=build /usr/src/app/next.config.js ./

COPY --from=build /usr/src/app/package*.json ./
COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/node_modules ./node_modules

# Enable APM Insight Node.js Agent
RUN mkdir -p /usr/src/app/apminsightdata && chown -R node:node /usr/src/app/apminsightdata

# Enable logging
RUN mkdir -p /var/log/nodejs && touch /var/log/nodejs/nodejs.log && chown -R node:node /var/log/nodejs

# Add startup scripts
COPY start_web.sh /usr/local/bin/start_web.sh
RUN chmod +x /usr/local/bin/start_web.sh && ln -s /usr/local/bin/start_web.sh /

# Harden Image
# COPY ./harden.sh .
# RUN chmod +x harden.sh && \
#     sh harden.sh && \
#     rm -f harden.sh

# Force container to run as a non-root user
USER node
