version: '3'

services:
  ebisusbay-web:
    container_name: ebisusbay-web
    restart: always
    read_only: true
    build:
      context: .
      dockerfile: Dockerfile_local
    environment:
      PORT: '3000'
      NEXT_PUBLIC_ENV: development
      # APMINSIGHT_ENABLED: 'false'
      # APMINSIGHT_LICENSE_KEY: us_25e4846c624d0af156763484be1e7e31
      # APMINSIGHT_APP_NAME: local-ebisusbay-web-arm64-us-east-1
      # APMINSIGHT_APP_PORT: '3000'
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    tmpfs:
      - /home/node/.npm/_logs:mode=770,uid=1000,gid=1000
      - /home/node/.npm/_cacache:mode=770,uid=1000,gid=1000
      - /tmp:mode=770,uid=1000,gid=1000
    volumes:
      - ./volumes/ebisusbay-web_logs:/var/log/nodejs:rw
      - ./volumes/ebisusbay-web_cache:/usr/src/app/.next/cache:rw
      # - ./volumes/ebisusbay-web_apminsight:/usr/src/app/apminsightdata:rw
    ports:
      - 3000:3000

  ebisusbay-web-nginx:
    container_name: ebisusbay-web-nginx
    restart: always
    read_only: true
    build:
      context: .
      dockerfile: ./proxy/Dockerfile_local
    environment:
      ## NGINX Amplify Agent
      AMPLIFY_API_KEY: b7f1ca270e79d8dc6350cd837b2b006b
      AMPLIFY_ENABLED: false
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/lib/nginx
      - /etc/amplify-agent/custom
      - /tmp
    volumes:
      - ./volumes/ebisusbay-web-nginx_logs:/var/log/nginx:rw
      - ./volumes/ebisusbay-web-nginx_amplify_logs:/var/log/amplify-agent:rw"
    ports:
      - 8080:8080
    depends_on:
      - ebisusbay-web
    links:
      - ebisusbay-web
